---
- hosts: new-nodes
  gather_facts: True
  remote_user: admin

  tasks:        
    - name: create user
      become: True
      user: 
        name: evens
        shell: /bin/bash
        password: $6$zjDaVo9td8Z6unvZ$28zHCHfLnUlaFLK3KmccVZOKyw.h1JFy4SqMEFi0kxuuWErzPcIpH.Pw78KhfgwHzCZXfEKa/YZLtVb.XERS60
        groups: sudo
        append: yes
        #sudo pip install passlib
        #python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.using(rounds=5000).hash(getpass.getpass())"

    - name: create dir
      become: True
      file:
        path: /home/evens/.ssh
        state: directory
        owner: evens
        group: evens
        mode: 0755

    - name: copy authorized_keys
      become: True
      copy:
        src: "{{ playbook_dir }}/files/authorized_keys"
        dest: /home/evens/.ssh/authorized_keys
        owner: evens
        group: evens
        mode: 0600