---
- hosts: localhost
  gather_facts: True

  vars: 
    template:
      jessie: 'local:vztmpl/debian-8.0-standard_8.7-1_amd64.tar.gz'
      stretch: 'infra-nas:vztmpl/debian-9.0-standard_9.3-1_amd64.tar.gz'

  vars_files: 
    - vars/proxmox3.yml

  tasks: 
    - name: create container
      register: create
      with_items: 
        - "{{ vmid }}"
      tags: create
      proxmox:
        vmid: "{{ item }}"
        node: '{{ proxmox_node }}'
        api_host: '{{ proxmox_api_host }}'
        api_user: '{{ proxmox_api_user }}'
        api_password: '{{ proxmox_api_password }}'
        hostname: "{{ hostname }}"
        password: '{{ proxmox_password_new_node }}'      
        ostemplate: "{{ template[os_version | default('stretch')] }}"
        pubkey: '{{ proxmox_pub_key }}'
        netif: '{"net0":"name=eth0,ip=dhcp,ip6=dhcp,bridge=vmbr0"}'
        cores: 1
        storage: local
        memory: 2048
        swap: 1048
        disk: 8
        force: yes

    - debug: { var: create.msg }
      tags: create

    - name: start container
      register: start
      tags: start
      with_items: '{{ vmid }}'
      proxmox:
        vmid: '{{ item }}'
        api_user: '{{ proxmox_api_user }}'
        api_password: '{{ proxmox_api_password }}'
        api_host: '{{ proxmox_api_host }}'
        state: started

    - debug: { var: start.msg }
      tags: start

    - name: stop container
      register: stop
      tags: stop
      with_items: '{{ vmid }}'
      proxmox:
        vmid: '{{ item }}'
        api_user: '{{ proxmox_api_user }}'
        api_password: '{{ proxmox_api_password }}'
        api_host: '{{ proxmox_api_host }}'
        force: yes
        state: stopped
      when: stopt is defined

    - debug: { var: stop.msg }
      tags: stop

    - name: remove container
      register: remove
      tags: remove
      with_items: '{{ vmid }}'
      proxmox:
        vmid: '{{ item }}'
        api_user: '{{ proxmox_api_user }}'
        api_password: '{{ proxmox_api_password }}'
        api_host: '{{ proxmox_api_host }}'
        state: absent
      when: stopt is defined

    - debug: { var: remove.msg }
      tags: remove
